name: Publish Release

on:
		 push:
					tags:
							 - "**"
		 workflow_dispatch:
jobs:
		 publish:
					name: Publish
					runs-on: ubuntu-latest
					steps:
							 - name: Checkout repository
								 uses: actions/checkout@v4

							 - name: Install Rust
								 uses: dtolnay/rust-toolchain@stable

							 - name: Create release
								 run: just create-release

							 - name: Build package
								 id: export
								 run: echo "zip=$(cat ./target/release/fox32asm-*-x86_64-linux.zip)" >> "$GITHUB_OUTPUT"

							 - name: Publish artifacts
								 uses: ncipollo/release-action@v1
								 with:
											artifacts: "${{ steps.export.outputs.zip }}"
											draft: true